### ISSUE TITLE
Reverse search?

### ISSUE THREAD

**Issue by devyboy** [gideontong/kiwi-hackathon#12]
I was just thinking, let's say the user already knows which plant they're looking at and they just want the info about it. We should just let them search by name or keyword to skip the whole "identifying" process. It would be easy, the api has an endpoint for that already.

https://docs.trefle.io/docs/guides/searching

@amp5 @gideontong

**Comment by gideontong** [comment]
Consider it done by tonight.

**Comment by gideontong** [comment]
Opened branch `reverse-search`
