### ISSUE TITLE
Hide certain fields if toxic

### ISSUE THREAD

**Issue by devyboy** [gideontong/kiwi-hackathon#13]
If the plant is any toxicity level other than none, we should hide certain fields that identify the fruit or seeds just as a safety measure. Is this a dumb idea or not. I'm just worried someone is going to miss the toxic part and be fixated on the fruit or something. Lemme hear your thoughts.

@amp5 @gideontong

**Comment by devyboy** [comment]
Actually I dont think this is a good idea, those are cool fields that I want the users to see still. We should just make it very clear about the toxicity possibly with some sort of attention grabbing disclaimer

**Comment by gideontong** [comment]
If level of toxicity is not important, I can write the API to return some field like `is_toxic` as a boolean.

**Comment by devyboy** [comment]
I think it would be cool to display the level of toxicity, like increasing warnings for the higher it is.

**Comment by gideontong** [comment]
Sure. Do you want an integer 0-4 or a floating point value?

**Comment by devyboy** [comment]
Integer is fine

**Comment by gideontong** [comment]
Yup, integer it was. No changes needed here.
