### ISSUE TITLE
flower search

### ISSUE THREAD

**Issue by amp5** [gideontong/kiwi-hackathon#20]
@devyboy  can you add white as an option for flower color?
I'm not seeing it in https://dice-game-d967b.web.app/id

**Comment by devyboy** [comment]
Those were just some quick placeholders i threw in there. Is there any way you can find a list of all the possible colors in the API reference?

**Comment by devyboy** [comment]
I'm just worried they have colors like 'beige' or something that I didn't account for

**Comment by amp5** [comment]
I'm not seeing in the docs any reference to the different color options. Maybe just stick with the 11 basic colors and we should be good:

White, Black, Grey, Yellow, Red, Blue, Green, Brown, Pink, Orange, Purple
