### ISSUE TITLE
Front End drop down menu options

### ISSUE THREAD

**Issue by amp5** [gideontong/kiwi-hackathon#6]
@devyboy 
When you are creating a way to filter the users query we can only use the following regions:

|  id  | name  |
|---|---|
|  602 | North-Central U.S.A.  |
| 603  | Northeastern U.S.A.  |
| 604  | Southwestern U.S.A.  |
| 605  | South-Central U.S.A.  |
| 606  | Southeastern U.S.A.  |
| 596  | Subarctic America  |
| 601  | Northwestern U.S.A.  |

Can you map it so that if a user selected the name, the id to that name is used as a parameter for the query?

**Comment by amp5** [comment]
Oh and the filter options I have so far are:
1. Region
2. Foliage Color
3. Flower Color
4. Fruit Color

If none are selected for numbers 2-3 return ''. Only number 1 needs to be mandatory although it might help if 1 and 2 are mandatory since the user should see the color of the leaves.

**Comment by devyboy** [comment]
Beautiful, I'll get on it.

**Comment by devyboy** [comment]
Created branch `basic-search-page`
