### ISSUE TITLE
Fields to show user

### ISSUE THREAD

**Issue by amp5** [gideontong/kiwi-hackathon#7]
How do we feel about returning the following bits of info to the user per plant:

- common_name - could be multiple names separated by | <- maybe get first one?
- image_url
- edible_part 
- is_edible
<del> - is_vegetable - maybe not necessary if we have is edible? <del>
- flower_img 
- leaf_img 
- habit_img - don't know what this image is yet. TBD
- fruit_img 
- bark_img 
- other_img 
- fruit_color - in case they don't know fruit color 
- toxicity

Let me know if you think we should get additional info

@devyboy  @gideontong

**Comment by gideontong** [comment]
I like these. Let's build an API for this. I'll get started tonight. Expect some code contribution before standup tomorrow.

**Comment by devyboy** [comment]
I think we can toss the `is_vegetable` since that seems a little out of place? Everything else seems good to me, great work.

**Comment by gideontong** [comment]
Sounds good. Everything except `is_vegetable`

**Comment by amp5** [comment]
Not sure if we want all the images for each plant. It would depend on the f/e format. refer to #5 for current json format for f/e

**Comment by gideontong** [comment]
Can return n number of random images or all if not specified. Decreases size of return object.
